// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANcfkHdnFC3cApwWhir-u7gwGwfrWTqTM',
    appId: '1:39714891069:web:a21724586abc855d091154',
    messagingSenderId: '39714891069',
    projectId: 'needle-network',
    authDomain: 'needle-network.firebaseapp.com',
    storageBucket: 'needle-network.appspot.com',
    measurementId: 'G-Z4YC9WF3ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB1hta8VN8t_jTfIcqTvk-xLkXGaJtkGg',
    appId: '1:39714891069:android:ddb829e22d746bf2091154',
    messagingSenderId: '39714891069',
    projectId: 'needle-network',
    storageBucket: 'needle-network.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTaenk1dU84tHLjfxWe0akzpqgKuLmsJA',
    appId: '1:39714891069:ios:89621aff90cb8ba8091154',
    messagingSenderId: '39714891069',
    projectId: 'needle-network',
    storageBucket: 'needle-network.appspot.com',
    androidClientId: '39714891069-5v157tr1v9mb0sbtlvum0jfdohuo4mf0.apps.googleusercontent.com',
    iosClientId: '39714891069-iigng29gafhq6ud53usum1k7nf60lcr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.needleNetworkMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTaenk1dU84tHLjfxWe0akzpqgKuLmsJA',
    appId: '1:39714891069:ios:89621aff90cb8ba8091154',
    messagingSenderId: '39714891069',
    projectId: 'needle-network',
    storageBucket: 'needle-network.appspot.com',
    androidClientId: '39714891069-5v157tr1v9mb0sbtlvum0jfdohuo4mf0.apps.googleusercontent.com',
    iosClientId: '39714891069-iigng29gafhq6ud53usum1k7nf60lcr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.needleNetworkMain',
  );
}
